### ISSUE TITLE
kubefirst local 1.10.9 - github-runner doesn't pick up jobs from a new repository

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1045]
unclear if this will be a problem on 1.11, but noticed during customer support tonight that after terraforming a new git repo, copying app code, .argo, .github, build folder, and renaming objects appropriately, the github action starts but never gets picked up by the runner.

deleting the runner pod doesn't allow it to pick up the job.

doesn't need to be fixed as a patch for 1.10, but we should be sure it's not an issue on 1.11.

to recreate:
- kubefirst local for a new k1 stack
- atlantis pr to add a new repo called metaphor-new
- copy all code from metaphor-go into metaphor-new
- globally replace metaphor-go to metaphor-new in all folder names and file content
- git commit and push, evaluate if job picks it up (job can fail due to gitops desired state directories not existing, but it cannot just hang like it does on 1.10.9)

**Comment by 6za** [comment]
This is not a bug exactly, it is a consequence the way the template is created and the limitation that we use "user" account, instead of a "organization" for hosting local repos. 


This template for the runner, enforces that the runner is deployed per-repository. 
https://github.com/kubefirst/gitops-template/blob/main/localhost/components/github-runner/runnerdeployment.yaml


On cloud, we use a org level set of runners, therefore this issue doesn't happen.

**Comment by 6za** [comment]
For the cloud deployment: 
https://github.com/kubefirst/gitops-template/blob/main/components/github-runner/github-runner.yaml#L32


To allow this new repo to be served by a runner, the user must got to this deployment, copy and create a new set of runner for the new repository to be observed.

**Comment by 6za** [comment]
My comments are based on the fact, that maybe we didn't update this runner definition here: 
_"globally replace metaphor-go to metaphor-new in all folder names and file content"_


Beyond of that it is not clear for me, where else could be the issue. 

Points to observe: 
- On the repo, if the runner it is well registered, it should be visible a self-hosted runner.
- On the local side, the runner pods usually mentions that is listening to github events

**Comment by 6za** [comment]
> git commit and push, evaluate if job picks it up (job can fail due to gitops desired state directories not existing, but it cannot just hang like it does on 1.10.9)

Could you provide more details on that?

**Comment by marinhojess** [comment]
I tried to reproduce this behavior by installing localhost using the main branch.

Steps: 

1. `go run . local --gitops-branch main --metaphor-branch main`


2. Added code block below to `gitops/terraform/github/repos.tf`:

```
# todo add organization support
module "metaphor" {
  source = "./modules/repository"
  visibility         = "private"
  repo_name          = "metaphor-new"
  archive_on_destroy = false
  auto_init          = true # set to false if importing an existing repository
}

resource "github_repository_webhook" "metaphor_atlantis_webhook" {
    repository = module.metaphor.repo_name
  
    configuration {
      url          = var.atlantis_repo_webhook_url
      content_type = "json"
      insecure_ssl = false
      secret       = var.atlantis_repo_webhook_secret
    }
  
    active = true
  
    events = ["pull_request_review", "push", "issue_comment", "pull_request"]
}
```

3. Open a PR to run atlantis apply

4. Copy all content from metaphor-go to metaphor-new

5. Added code block below to `gitops/components/github-runner/runnerdeployment.yaml`:

```
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-metaphor-new
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  replicas: 1
  template:
    spec:  
      repository: cicdk1/metaphor-new
      image: summerwind/actions-runner-dind
      serviceAccountName: github-runner
      dockerdWithinRunnerContainer: true
      automountServiceAccountToken: true
```

**After completing all previous steps, github runner was able to execute the action as expected.**
