### ISSUE TITLE
[Docs]: Add docs about use init with config yaml file

### ISSUE THREAD

**Issue by marinhojess** [kubefirst/kubefirst#1150]
### What type of suggestions?

Missing Information

### What page is concerned?

https://docs.kubefirst.com/preprod/kubefirst/github/install.html

### What is the issue?

Users can run init command along flags and configuration yaml file. The information about the configuration yaml file is missing on docs.

Users can run init command with the configuration yaml file as follows:

`kubefirst init -c some_config_file.yaml`

The content of file can use all flags of init command, in this case removing `--` from beginning of the flag:

```
config:
  cluster-name: some-cluster-name
  admin-email: some-email
  cloud: aws
  profile: default
  hosted-zone-name: some-hosted-zone
  s3-suffix: some-suffix
  region: us-east-1
  github-owner: github-owner
  bot-password: somepassword
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
