### ISSUE TITLE
[atlanits ngrok local] Create an in cluster pod with ngrok and use its API to discover webhook address

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#1227]
# Overview 

It seems we have a flaky solution for `atlantis` + `ngrok`. 

Current limitations: 
- https://github.com/kubefirst/kubefirst/issues/939
- IF the installer is finished(purple screen), the webhook is destroyed. 
- Connection seems to be broken without clear signas of why it is broken the pipe.

Note: This only impacts `local` due to its nature of been running on a laptop we need to leverage ngrok for emulating a public host. 

Solution:
- [ ] an in cluster pod running an ngrokCLI, that if failed the tunnel it restarts and creates a new one. (for free plans, creating a new external URL)
- [ ] a checker pod to check from time to time when final, due to limitations of free plans the checker will Update github instructions on github webhooks, to allow it keep always pointed to the correct atlantis Address

AC:

- [ ] To replace ngrok from the CLI side to a `in cluster` solution.

**Comment by 6za** [comment]
Webhook settings:

**Comment by 6za** [comment]
Sample deployment of a webhook + " fake checker":
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok-agent
spec:
  selector:
    matchLabels:
      app: ngrok-agent
  template:
    metadata:
      labels:
        app: ngrok-agent
    spec:
      containers:
      - args:
        - http
        - atlantis.atlantis.svc.cluster.local:80

        image: docker.io/ngrok/ngrok:3
        name: ngrok-agent
        ports:
        - containerPort: 4040
          name: web
        readinessProbe:
          httpGet:
            path: /status
            port: 4040
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: ngrok-agent
spec:
  ports:
  - name: web
    port: 4040
    targetPort: 4040
  selector:
    app: ngrok-agent
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok-checker
spec:
  selector:
    matchLabels:
      app: ngrok-checker
  template:
    metadata:
      labels:
        app: ngrok-checker
    spec:
      containers:
      - args:
        - ngrok-agent.argocd.svc.cluster.local:4040/api/tunnels
        image: docker.io/ibmcom/curl:4.0.0
        name: ngrok-checker
```
