### ISSUE TITLE
Feat: Add CloudFlare as an option for DNS upon creation instead of Provider implementaton

### ISSUE THREAD

**Issue by brenjay** [kubefirst/kubefirst#1645]
**What would you like to be added**:
Add option when provisioning a cluster to use CloudFlare's Authoritative DNS instead of the providers' (ex: AWS Route 53/Civo DNS). This acts as a vendor neutral provider that can work across the board with the addition of being able to use CF extras like caching or CF access out of the gate after cluster provisioning. One could generate a CF API Token and pass this to kubefirst during setup. I was able to successfully get CF working via a slight modification to the external-dns configuration, when deployed to Civo. This could be an easy win to implement, at first glance at least for using with Civo instead of their DNS.

To get this working; In gitops I modified the helm entry of registry/kubefirst/components/external-dns/application.yaml to the following:

```
helm:
      releaseName: external-dns
      values: |
        extraArgs: ['--cloudflare-proxied']
        image:
          repository: registry.k8s.io/external-dns/external-dns
          tag: "v0.13.2"
        serviceAccount:
          create: true
          name: external-dns
        provider: cloudflare
        sources:
        - ingress
        domainFilters:
        - EXAMPLE.com
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: civo-creds #this would change to some CF specific secret
              key: civo-token #this would change to some CF specific secret
```
As an 'additional' note for anyone who plans on using CF Access (Or if you are using a similiar application proxy like IAP in GCP you need to pass the Host header to ArgoCD that CF seemingly stripped in my case.) I modified the annotations in gitops of registry/kubefirst/components/argocd/argocd-ui-ingress.yaml like the following:

```
annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
``` 
**Why is this needed**:
There are a few uses cases where CloudFlare DNS must or could be used in lieu of the providers' implementation. 

* If a domain is created with certain registrars (ex: CloudFlare Registrar in this case) the name servers cannot be changed to use another platform. Civo requires you to change nameservers to utilize their DNS service, which is what is supported by kubefirst out of the box when provisioning a cluster there. Thus, someone who has a domain via CloudFlare registrar is forced to use their DNS which isn't currently supported out of the box by kubefirst; or transfer out to another registrar just to be able to change the nameservers to work with Civo DNS. 
* There may be a legacy or enterprise requirement to continue using CF as well. 
* Using CloudFlare DNS is an easy way to take advantage of other (even free) CF services by proxying via CF to use caching/DDOS protection/analytics etc.. 
* Another specific usage I am using CF for is to proxy Vault / Argo behind CloudFlare Access which allows for greater security so these sensitive components aren't publicly accessible.
