### ISSUE TITLE
[Bug] Argo Worflow Users Not allowed to load UI

### ISSUE THREAD

**Issue by Claywd** [kubefirst/kubefirst#1676]
### Which version of kubefirst are you using?

all

### Which cloud provider?

k3d (local)

### Which installation type?

CLI

### Which distributed Git provider?

GitHub

### What is the issue?

Trying to explore Argo Workflows on Kubefirst 2.1 but I keep getting an error in the UI : Unable to load data: {"code":7,"message":"not allowed"}. Any idea whats happening? This is true for both a developer user and an admin user. Maybe I need to make a namespace for the users? (edited) 

**https://kubefirst.slack.com/archives/C03U34WJ7FW/p1688765473467719**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johndietz** [comment]
note this has been identified on the beta vultr github stack as well when provisioned through the ui

**Comment by johndietz** [comment]
we've identified that while k8s 1.24 doesn't prevent the kubefirst automation from running in argo workflows, it is preventing ui access to users. this can be fixed by changing the file located in the `gitops` git repository at location
`registry/<clustername>/components/argo-workflows/serviceaccount.yaml`

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    # The rule is an expression used to determine if this service account
    # should be used.
    # * `groups` - an array of the OIDC groups
    # * `iss` - the issuer ("argo-server")
    # * `sub` - the subject (typically the username)
    # Must evaluate to a boolean.
    # If you want an account to be the default to use, this rule can be "true".
    # Details of the expression language are available in
    # https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md.
    workflows.argoproj.io/rbac-rule: "'admins' in groups"
    # The precedence is used to determine which service account to use whe
    # Precedence is an integer. It may be negative. If omitted, it defaults to "0".
    # Numerically higher values have higher precedence (not lower, which maybe
    # counter-intuitive to you).
    # If two rules match and have the same precedence, then which one used will
    # be arbitrary.
    workflows.argoproj.io/rbac-rule-precedence: '1'
secrets:
- name: argo-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-developer
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    workflows.argoproj.io/rbac-rule: "'developers' in groups"
    workflows.argoproj.io/rbac-rule-precedence: '0'
secrets:
- name: argo-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-admin
  annotations:
    kubernetes.io/service-account.name: argo-admin
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-developer
  annotations:
    kubernetes.io/service-account.name: argo-developer
type: kubernetes.io/service-account-token
```
