### ISSUE TITLE
allow crossplane cluster workspace management on pro

### ISSUE THREAD

**Issue by johndietz** [kubefirst/kubefirst#1949]
### What is your feature idea?

when a physical cluster is created in kubefirst console, and then proactively deleted in the cloud, crossplane will want to recreate it, but it detects drift. there's an annotation that needs to be removed from the cluster resource in kubernetes in order for it to recreate. it'd be amazing to surface when clusters are in this state to our pro users and allow them to remove the annotation right from our console ui.

### Why is it needed?

this status is on the cluster workspace object when you're in the described state
```
status:
  atProvider: {}
  conditions:
    - lastTransitionTime: '2023-12-08T20:40:27Z'
      reason: Creating
      status: 'False'
      type: Ready
    - lastTransitionTime: '2023-12-08T20:40:27Z'
      message: >-
        cannot determine creation result - remove the
        crossplane.io/external-create-pending annotation if it is safe to
        proceed
      reason: ReconcileError
      status: 'False'
      type: Synced
```

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
