### ISSUE TITLE
add GitHub automation bot for use in PRs/Issues

### ISSUE THREAD

**Issue by mrsimonemms** [kubefirst/kubefirst#2229]

**Comment by itsaviral2609** [comment]
Hi @mrsimonemms 
I have worked on something like this.
I will get this integrated if no one is working on this issue!

**Comment by mrsimonemms** [comment]
Great, it's yours. Thank you

**Comment by itsaviral2609** [comment]
Hi 

I just wanted to ask for few more details as if the ProBot needs to be just added from Github marketplace or need more custom ProBot specific with more details like the command you mentioned 
- /approve 
- /hold 
- /unhold with marking some issues stale and adding labels cause I built something like this in the past [https://github.com/itsaviral2609/Custom-GitHub-Bot-Next](url)

If it's the latter case, you can add any more details needed in bot for better user experience.

**Comment by itsaviral2609** [comment]
Hi @mrsimonemms 

I was working on the testing of this kubefirst bot and wanted some inputs based upon the feature of commands like /hold /approve and /unhold and marking issues and PR's stale. I have added stale.yaml workflow file which will be marking our issues and PRs stale down below(random values for testing purpose). 

1. Whether we want all old issues to be marked stale or mark only those issues stale after the time period app was installed on repo
2. Minimum number of maintainers check needed for approval of a PR (I have taken 2 while testing) and whether to take maintainer.yaml file or check for repo's collaborator? 
3. Do we want issues with label 'feature' not marked stale? and how many days after we mark them stale and and no of days before they get closed completely
4. Any other thing you will like to get added :)



Providing some Screenshots of results before I deploy the GitHub app based upon the modifications provided by the maintainers

```yaml
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight (UTC)
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue has been marked as stale due to inactivity. Please update if it is still relevant."
          stale-pr-message: "This pull request has been marked as stale due to inactivity. Please update if it is still relevant."
          stale-issue-label: "needs-attention"
          stale-pr-label: "needs-review"
          days-before-issue-stale: 5        # Number of days of inactivity before marking issues as stale
          days-before-pr-stale: 2          # Number of days of inactivity before marking PRs as stale
          days-before-issue-close: -1        # Do not automatically close issues
          days-before-pr-close: -1           # Do not automatically close PRs
          exempt-issue-labels: "hold,feature,in progress"  # Exempt these labels from being marked stale
          exempt-pr-labels: "hold"           # Exempt these labels from being marked stale
          remove-issue-stale-when-updated: true  # Remove stale label when issue is updated
          remove-pr-stale-when-updated: true     # Remove stale label when PR is updated
          include-only-assigned: false           # Include issues even if they have an assignee
```
# /approve command
![Screenshot from 2024-11-15 23-29-54](https://github.com/user-attachments/assets/1654ff84-10c6-45dd-9995-6a3600925b5a)
![Screenshot from 2024-11-15 23-30-19](https://github.com/user-attachments/assets/fcbc1673-ae08-48c0-84c5-2d019b5ac65d)
![Screenshot from 2024-11-15 23-30-50](https://github.com/user-attachments/assets/49cf74f1-4ccd-4dca-a1ff-1be2e4db20c4)

# /hold /unhold

![Screenshot from 2024-11-15 23-57-18](https://github.com/user-attachments/assets/8ca52e81-0747-44e4-aede-424470c8cc19)


# Stale PR
![Screenshot from 2024-11-15 23-45-33](https://github.com/user-attachments/assets/ad8b785d-e288-4db1-8941-51f09b1ef0cf)
