### ISSUE TITLE
Enhancement - Add tags on buckets

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#317]
# Overview 

To help cleaning installations artifacts to add the following tags on buckets created:

```yaml 
ProvisionedBy: kubefirst
ClusterName: <CLUSTER_NAME>
InstalledBy: <EMAIL_ADDRESS>
```

If we have privacy concerns on adding the user email on the tags, we can add a [hash](https://stackoverflow.com/questions/10701874/generating-the-sha-hash-of-a-string-using-golang) from that string, just to generate a unique ID per installer person.
