### ISSUE TITLE
1.9.x - Issue to clone repo in github mode - cwfts

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#330]
# Overview

CWFT when using a private github repo, our current key is failing to be accepted by github:
```bash
time="2022-09-07T01:31:13.071Z" level=fatal msg="artifact gitops-source failed to load: unknown error: ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type."
```

Sample artifact read: 
```yaml 
      - name: gitops-source
        path: /src/gitops
        git:
          repo: "ssh://git@github.com/org-demo-6za/gitops.git"
          revision: "main"
          insecureIgnoreHostKey: true
          sshPrivateKeySecret:
            name: ssh-key-secret
            key: ssh-privatekey   
```

# Note 

if used this key process for creation: 
```bash 
 ssh-keygen -t ed25519 -C "your_email@example.com"
```

And then loaded key to the secret above, clone will work as expected.
