### ISSUE TITLE
1.9.x - CWFTs need to be adjusted to support github auth mode (SSH)

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#331]
# Overview 

Actions: 
- Private key need to be loaded by [terraform secret](https://github.com/kubefirst/gitops-template/blob/main/terraform/vault/bootstrap/secrets.tf#L33) to store the private SSH key, so cwfts can load it. 
- CWFTs need to be adjusted, got gitlab they are based on user/pwd, but github artifacts should be loaded using ssh keys. 

Sample:
```yaml 
      - name: gitops-source
        path: /src/gitops
        git:
          repo: "ssh://git@github.com/org-demo-6za/gitops.git"
          revision: "main"
          insecureIgnoreHostKey: true
          sshPrivateKeySecret:
            name: ssh-key-secret
            key: ssh-privatekey 
```

# Note 

Github clone mode is based on SSH clone, token based clone or user/password it seems to not work as expected at the moment.
