### ISSUE TITLE
github install - chartmusuem not available yet.

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#386]
# Overview

As is, metaphors application once pushed will execute the build job, and if that happens too early chartmuseum is not ready yet. 

```bash 
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-908752723: version: 0.1.0-rc.b9f797532946451b3c226fbce2d7b324f
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832: Error: looks like "https://chartmuseum.6zray.kubefast.com/" is not a valid chart repository or cannot be reached: Get "https://chartmuseum.6zray.kubefast.com/index.yaml": dial tcp: lookup chartmuseum.6zray.kubefast.com on 172.20.0.10:53: no such host
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832: Error: couldn't load repositories file (/root/.config/helm/repositories.yaml): open /root/.config/helm/repositories.yaml: no such file or directory
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832: Usage:
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832:   helm push [flags]
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832: 
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832: Flags:
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832:       --access-token string             Send token in Authorization header [$HELM_REPO_ACCESS_TOKEN]
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832:       --auth-header string              Alternative header to use for token auth [$HELM_REPO_AUTH_HEADER]
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832:       --ca-file string                  Verify certificates of HTTPS-enabled servers using this CA bundle [$HELM_REPO_CA_FILE]
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832:       --cert-file string                Identify HTTPS client using this SSL certificate file [$HELM_REPO_CERT_FILE]
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832:       --check-helm-version              outputs either "2" or "3" indicating the current Helm major version
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832:       --context-path string             ChartMuseum context path [$HELM_REPO_CONTEXT_PATH]
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832:       --debug                           Enable verbose output
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832:   -d, --dependency-update               update dependencies from "requirements.yaml" to dir "charts/" before packaging
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832:   -f, --force                           Force upload even if chart version exists
metaphor-publish-b9f797532946451b3c226fbce2d7b324fz2ftz-1555305832:   -h, --help                            help for helm
```

**Comment by 6za** [comment]
pr merged

**Comment by 6za** [comment]
Solution above didn't worked. Chartmusuem stills takes a bit to be ready, jobs failed. 

Next possible solution is to ask argo the state of the deployment, before proceeding: 
<img width="789" alt="image" src="https://user-images.githubusercontent.com/53096417/190631495-a5ac38cd-6b14-4b73-b548-98c3bfa81b8d.png">

If all is "OK" and Synched.. to proceed.

**Comment by 6za** [comment]
Issue persists, argo is ready. but `chart-musuem` still need time to be ready. 

```bash
metaphor-publish-7fbd8ce1f9947e8cf9d01072a0f5cee5dndlk6-3753879044: Error: looks like "https://chartmuseum.6zray.kubefast.com/" is not a valid chart repository or cannot be reached: Get "https://chartmuseum.6zray.kubefast.com/index.yaml": dial tcp: lookup chartmuseum.6zray.kubefast.com on 172.20.0.10:53: no such host
metaphor-publish-7fbd8ce1f9947e8cf9d01072a0f5cee5dndlk6-3753879044: Error: couldn't load repositories file (/root/.config/helm/repositories.yaml): open /root/.config/helm/repositories.yaml: no such file or directory
metaphor-publish-7fbd8ce1f9947e8cf9d01072a0f5cee5dndlk6-3753879044: Usage:
metaphor-publish-7fbd8ce1f9947e8cf9d01072a0f5cee5dndlk6-3753879044:   helm push [flags]
metaphor-publish-7fbd8ce1f9947e8cf9d01072a0f5cee5dndlk6-3753879044: 
metaphor-publish-7fbd8ce1f9947e8cf9d01072a0f5cee5dndlk6-3753879044: Flags:
metaphor-publish-7fbd8ce1f9947e8cf9d01072a0f5cee5dndlk6-3753879044:       --access-token string             Send token in Authorization header [$HELM_REPO_ACCESS_TOKEN] 
```

**Comment by 6za** [comment]
The mechanism worked as expected:
- Waited deployments to be synched. 
- Then deployed metaphor

```bash
LOG: 2022/09/19 14:14:50.570164 /home/developer/app/cmd/k1Ready.go:49: argo forwarded called
LOG: 2022/09/19 14:14:50.571197 /home/developer/app/cmd/k1Ready.go:36: Closed argoCD port forward
LOG: 2022/09/19 14:14:50.571471 /home/developer/app/cmd/create.go:70: Post "https://localhost:8080/api/v1/session": dial tcp 127.0.0.1:8080: connect: connection refused
LOG: 2022/09/19 14:14:50.571865 /home/developer/app/cmd/k1Ready.go:27: argocdAppStatus called
LOG: 2022/09/19 14:14:50.572066 /home/developer/app/internal/flagset/common.go:58: Enviroment Variable(dry-run) not set
LOG: 2022/09/19 14:14:50.572284 /home/developer/app/internal/flagset/common.go:58: Enviroment Variable(use-telemetry) not set
LOG: 2022/09/19 14:14:50.572448 /home/developer/app/internal/flagset/common.go:58: Enviroment Variable(silent) not set
LOG: 2022/09/19 14:14:50.573221 /home/developer/app/internal/k8s/kubernetes.go:185: PF started (svc/argocd-server)
LOG: 2022/09/19 14:14:55.573530 /home/developer/app/internal/k8s/kubernetes.go:193: /home/developer/.k1/tools/kubectl   --kubeconfig   /home/developer/.k1/gitops/terraform/base/kubeconfig   -n   argocd   port-forward   svc/argocd-server   8080:80
LOG: 2022/09/19 14:14:55.574405 /home/developer/app/cmd/k1Ready.go:49: argo forwarded called
LOG: 2022/09/19 14:14:58.401370 /home/developer/app/internal/argocd/argocd.go:455: App status: Synced
LOG: 2022/09/19 14:14:58.401696 /home/developer/app/cmd/k1Ready.go:62: App registry is synched: true
LOG: 2022/09/19 14:14:59.579736 /home/developer/app/internal/argocd/argocd.go:455: App status: Synced
LOG: 2022/09/19 14:14:59.580078 /home/developer/app/cmd/k1Ready.go:62: App argocd is synched: true
LOG: 2022/09/19 14:15:00.507031 /home/developer/app/internal/argocd/argocd.go:455: App status: Synced
LOG: 2022/09/19 14:15:00.507478 /home/developer/app/cmd/k1Ready.go:62: App atlantis is synched: true
LOG: 2022/09/19 14:15:01.672400 /home/developer/app/internal/argocd/argocd.go:455: App status: Synced
LOG: 2022/09/19 14:15:01.672826 /home/developer/app/cmd/k1Ready.go:62: App cert-manager is synched: true
LOG: 2022/09/19 14:15:02.638377 /home/developer/app/internal/argocd/argocd.go:455: App status: Synced
LOG: 2022/09/19 14:15:02.638936 /home/developer/app/cmd/k1Ready.go:62: App chartmuseum is synched: true
LOG: 2022/09/19 14:15:03.564805 /home/developer/app/internal/argocd/argocd.go:455: App status: Synced
LOG: 2022/09/19 14:15:03.565315 /home/developer/app/cmd/k1Ready.go:62: App chartmuseum-components is synched: true
LOG: 2022/09/19 14:15:03.565774 /home/developer/app/cmd/k1Ready.go:36: Closed argoCD port forward
LOG: 2022/09/19 14:15:03.566206 /home/developer/app/cmd/createUtils.go:303: Deploying metaphor applications
```

Time match github side logs: 
```
commit sha c0b009d7fbd8ce1f9947e8cf9d01072a0f5cee5d
argo: v3.1.11
Name:                metaphor-publish-7fbd8ce1f9947e8cf9d01072a0f5cee5dndlk6
Namespace:           argo
ServiceAccount:      argo
Status:              Pending
Created:             Mon Sep 19 14:15:[25](https://github.com/org-demo-6za/metaphor/actions/runs/3083112467/jobs/4983641369#step:9:26) +0000 (now)
Progress:            
Parameters:          
  appName:           metaphor
  ciCommitSha:       c0b009d7fbd8ce1f9947e8cf9d01072a0f5cee5d
  branch:            main
```

**Comment by 6za** [comment]
Next idea is to try add a curl(loop) to wait chart museum to be ready.

**Comment by 6za** [comment]
Issue when cwft is not ready after installer did its job:
```bash
Run echo "commit sha $GITHUB_SHA"
commit sha 7bfee0a8c33db05ce6b17843e41168101fef30a5
argo: v3.1.11
time="[20](https://github.com/org-demo-6za/metaphor-go/actions/runs/3084632269/jobs/4987002465#step:9:21)[22](https://github.com/org-demo-6za/metaphor-go/actions/runs/3084632269/jobs/4987002465#step:9:23)-09-19T18:13:01.314Z" level=fatal msg="Failed to submit workflow: templates.main.steps[0].checkout template reference cwft-git.git-checkout-with-gitops-ssh not found"
Error: Process completed with exit code 1.
```

**Comment by 6za** [comment]
https://github.com/kubefirst/metaphor-template/pull/9 - works as expected. 

Eventually, name resolution is ready on the cluster side and job work as expected on get-go.

```
aphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-4111283887: 0.1.0
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1701409132: setting ./charts/metaphor/Chart.yaml to version: 0.1.0-rc.42e85626aa8b7ad9a1308df6002595a27
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1701409132: setting charts/metaphor/Chart.yaml to appVersion: 2f2a6fb42e85626aa8b7ad9a1308df6002595a27
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1701409132: adjusted chart:
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1701409132: apiVersion: v2
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1701409132: appVersion: 2f2a6fb42e85626aa8b7ad9a1308df6002595a27
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1701409132: description: A Helm chart for Kubernetes
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1701409132: name: metaphor
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1701409132: type: application
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1701409132: version: 0.1.0-rc.42e85626aa8b7ad9a1308df6002595a27
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-3319894616:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-3319894616:                                  Dload  Upload   Total   Spent    Left  Speed
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-3319894616: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: chartmuseum.6zray.kubefast.com
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-3319894616: waiting before trying again
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-3521078949:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-3521078949:                                  Dload  Upload   Total   Spent    Left  Speed
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-3521078949: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: chartmuseum.6zray.kubefast.com
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-3521078949: waiting before trying again
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1776059478:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1776059478:                                  Dload  Upload   Total   Spent    Left  Speed
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1776059478: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: chartmuseum.6zray.kubefast.com
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1776059478: waiting before trying again
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1171918099:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1171918099:                                  Dload  Upload   Total   Spent    Left  Speed
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1171918099: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: chartmuseum.6zray.kubefast.com
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1171918099: waiting before trying again
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1307[271](https://github.com/org-demo-6za/metaphor/actions/runs/3090260096/jobs/4998828982#step:9:272)884:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1307271884:                                  Dload  Upload   Total   Spent    Left  Speed
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1307271884: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: chartmuseum.6zray.kubefast.com
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1307271884: waiting before trying again
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1776898121:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1776898121:                                  Dload  Upload   Total   Spent    Left  Speed
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1776898121: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: chartmuseum.6zray.kubefast.com
metaphor-publish-42e85626aa8b7ad9a1308df600[259](https://github.com/org-demo-6za/metaphor/actions/runs/3090260096/jobs/4998828982#step:9:260)5a27w2xx4-1776898121: waiting before trying again
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1374088170:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1374088170:                                  Dload  Upload   Total   Spent    Left  Speed
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1374088170: apiVersion: v1
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1374088170: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    76  100    76    0     0    835      0 --:--:-- --:--:-- --:--:--   826
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1374088170: entries: {}
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1374088170: generated: "2022-09-20T12:44:32Z"
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-1374088170: serverInfo: {}
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-45834735: "kubefirst" has been added to your repositories
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-45834735: Pushing metaphor-0.1.0-rc.42e85626aa8b7ad9a1308df6002595a27.tgz to kubefirst...
metaphor-publish-42e85626aa8b7ad9a1308df6002595a27w2xx4-45834735: Done.
```

PR Zero:  Worked as expected! 
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/53096417/191264623-eb209134-ad15-4ab6-ae75-032f697c8345.png">

<img width="898" alt="image" src="https://user-images.githubusercontent.com/53096417/191264670-5882c549-7be0-4653-8dc5-3c1431a52b7a.png">

**Comment by 6za** [comment]
Last updated worked for 2/3 of the metaphor repos. 

Although, the first one to trigger the action `metaphor` worked for some iterations, until it failed to get a CWFT, that was checked to exist in the cluster: 

``` 
    metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j-1739604073:
      boundaryID: metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j
      children:
      - metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j-2367557840
      - metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j-2031858365
      - metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j-286838894
      - metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j-3977664811
      - metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j-4113018596
      - metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j-287677537
      - metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j-2569183458
      displayName: publish-check-cm
      finishedAt: "2022-09-20T16:28:58Z"
      id: metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j-1739604073
      inputs:
        artifacts:
        - name: repo-source
          path: /src
          s3:
            key: argo/artifacts/2022/09/20/365ae5e2-e167-45a0-b758-8ae1058f00ba/metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j/metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j-1163116052/repo-source.tgz
        parameters:
        - name: appDir
          value: /src/metaphor
        - default: kubefirst/chubbo:0.1
          name: buildImage
          value: kubefirst/chubbo:0.1
        - name: chartDir
          value: charts/metaphor
        - default: kubefirst
          name: chartRepoName
          value: kubefirst
        - default: ...
          name: chartRepoUrl
          value: ...
      message: clusterworkflowtemplates.argoproj.io "cwft-helm" not found
      name: metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j[4].publish-check-cm
      phase: Error
      progress: 7/7
      resourcesDuration:
        cpu: 152
        memory: 152
      startedAt: "2022-09-20T16:26:26Z"
      templateRef:
        clusterScope: true
        name: cwft-helm
        template: helm-check-chart-museum
      templateScope: local/metaphor-publish-901e87bccb65a20ed10ec75c17837d45f5j85j
      type: Retry
```



"clusterworkflowtemplates.argoproj.io "cwft-helm" not found" ...
