### ISSUE TITLE
Fix namespace

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#470]
```yaml 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: external-secrets-for-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  project: default
  source:
    repoURL: https://gitlab.6zray.kubefast.com/kubefirst/gitops.git
    path: components/external-secrets-for-argocd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

`  namespace: external-secrets-for-argocd` ot needs to be argocd
