### ISSUE TITLE
# Bug - gitlab install asking github token

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#639]
# Output
```bash 
2022/11/02 17:00:58 kubefirst started
Logging at: /home/developer/app/logs/log_1667408458.log
LOG: 2022/11/02 17:00:58.733685 /home/developer/app/pkg/helpers.go:270: Using config file: /home/developer/.kubefirst
-----------


  ----------------------------------------------------------------------
  Info summary:
  ----------------------------------------------------------------------

  Operational System: linux
  Architecture: amd64
  Go Lang version: vgo1.18.6
  Kubefirst config file: /home/developer/.kubefirst
  Kubefirst config folder: /home/developer/.k1
  Kubectl path: /home/developer/.k1/tools/kubectl
  Terraform path: /home/developer/.k1/tools/terraform
  Kubeconfig path: /home/developer/.k1/gitops/terraform/base/kubeconfig
  Kubefirst Version: 1.10.1





  ---------------------------------------------------------------------
  No GITHUB_AUTH_TOKEN env variable found!
  Use the code below to get a temporary GitHub Personal Access Token and
  continue
  ---------------------------------------------------------------------
... suppressed ...

  2. paste the code at the GitHub page: https://github.com/login/device
  3. authorize your organization

  A GitHub Personal Access Token is required to provision GitHub
  repositories and run workflows in GitHub.

```

# Config

`./logs/aws_install.yaml`:
```yaml 
config:
  admin-email:  my@email.com
  cloud: aws
  region: us-east-1
  hosted-zone-name: my.domain.com
  profile: default
  bot-password: mypassword
  gitops-branch: main
  metaphor-branch: main
  s3-suffix: my-bucket-suffix
  cluster-name: clustername
  aws-nodes-spot: true
 
```

Gitlab install.

```bash 
docker run \
  -v  go-pkg:/go/pkg \
  -v /Users/kaxios/_DEV/_public/6za/keys:/home/developer/.ssh/ \
  -it --name $BRANCH  \
  --dns="1.0.0.1" --dns="208.67.222.222" --dns="8.8.8.8" \
  -v $(PWD):/home/developer/app \
   cobra_dev
```

**Comment by 6za** [comment]
It seems to be related to early reading of flags on init: 
https://github.com/kubefirst/kubefirst/blob/main/cmd/init.go#L46

This flags are not supported to be passed in main at the moment: 
```bash 
export KUBEFIRST_CLOUD=aws
export KUBEFIRST_GIT_PROVIDER=gitlab
```

Forcing installer to fallback to github mode by default.

**Comment by converge** [comment]
I think I had the same issue. we can mitigate that isolating the gitlab create, it will avoid the `if` instatement to check if it's a gitlab or github install

**Comment by 6za** [comment]
Why we have a github runner in a gitlab install?
```bash 
external-dns                external-dns-545795f4bf-t7cj8                                1/1     Running             0          5m49s
external-secrets-operator   external-secrets-operator-754754dfbb-m9nvj                   1/1     Running             0          5m29s
external-secrets-operator   external-secrets-operator-cert-controller-64fb84c4dd-p824h   1/1     Running             0          5m29s
external-secrets-operator   external-secrets-operator-webhook-889c56c7b-qbzlc            1/1     Running             0          5m29s
github-runner               actions-runner-controller-5dd9cc6795-frwlf                   0/2     ContainerCreating   0          5m31s
ingress-nginx               ingress-nginx-controller-777cccdc76-lz2gg                    1/1     Running             0          5m50s
kube-system                 aws-node-4jrc8                                               1/1     Running             0          10m
kube-system                 aws-node-89brw                                               1/1     Running             0          11m
kube-system                 aws-node-cblkr                                               1/1     Running             0          10m
```

**Comment by 6za** [comment]
```yaml 
create:
  repos:
    soft:
      gitops:
        pushed: true
  softserve:
    configure: true
    create: true
    ready: true
  terraformapplied:
    base: true
createdby: installer
git:
  clone:
    gitops:
      branch: main
  mode: gitlab
github:
  atlantis:
    webhook:
      secret: --suppress--
  host: github.com
  owner: ""
  user: ""
gitlab:
  local:
    service: http://localhost:8888
gitops:
  branch: main
  owner: kubefirst
  repo: gitops
gitprovider: gitlab
```
